trigger: 
  branches:
    include:
      - master
      - develop
pr:
  branches:
    include:
      - master

jobs:

  - job: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    - script: |
        yarn
      displayName: 'Install packages'
    - script: |
        yarn test
      displayName: 'Run unit tests'

  - job: Deploy
    dependsOn: Test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) # Assert master
    steps:
    - script: echo "To implement"