version: "3.9"
services:

  store:
    container_name: store
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"

  database:
    container_name: database
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: open_market_api
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password

  api:
    container_name: service-api
    build: .
    links:
      - database
      - store
    volumes:
      - ./src:/app/src
    command: sh -c "yarn start:server-dev"
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      REDIS_URL: 'redis://store:6379'

  worker:
    container_name: worker-api
    build: .
    links:
      - database
      - store
    volumes:
      - ./src:/app/src
    command: sh -c "yarn start:server-dev"
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      REDIS_URL: 'redis://store:6379'
