version: "3.8"
services:

  database:
    container_name: service-database
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    container_name: service-api
    image: library/node:14-alpine
    links:
      - database
    volumes:
      - .:/home/service-api
    working_dir: /home/service-api
    command: sh -c "yarn && yarn dev"
    ports:
      - 3000:3000
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: database
      TYPEORM_USERNAME: admin_user
      TYPEORM_PASSWORD: admin_password
      TYPEORM_DATABASE: api
      TYPEORM_PORT: 5432
