api:
  http:
    port: PORT
  auth:
    jwt-signature: JWT_SIGNATURE
  logs:
    local: LOGS
    distant: LOGS_DISTANT
database:
  postgres:
    details:
      host: POSTGRES_HOST
      port: POSTGRES_PORT
      username: POSTGRES_USER
      password: POSTGRES_PASSWORD
      database: POSTGRES_DB
    url: DATABASE_URL
services:
  elastic:
    apm-url: APM_URL
    apm-secret: APM_SECRET
    cloud-id: ELASTIC_CLOUD_ID
    log-api-id: ELASTIC_LOG_API_ID
    log-api-key: ELASTIC_LOG_API_KEY
  mixpanel:
    secret: MIXPANEL_SECRET