api:
  http:
    port: PORT
  auth:
    jwtSecret: JWT_SECRET
    sessionSecret: SESSION_SECRET
  logs:
    local: LOGS
    distant: LOGS_DISTANT
database:
  mongo:
    url: DATABASE_URL
services:
  mixpanel:
    secret: MIXPANEL_SECRET
  sentry:
    dsn: SENTRY_DSN