api:
  env: NODE_ENV
  http:
    port: PORT
  auth:
    jwtSecret: JWT_SECRET
    sessionSecret: SESSION_SECRET
  logs:
    local: LOGS
    distant: LOGS_DISTANT
services:
  mixpanel:
    secret: MIXPANEL_SECRET
  sentry:
    dsn: SENTRY_DSN
