api:
  env: NODE_ENV
  http:
    port: PORT
  auth:
    jwtSecret: JWT_SECRET
    sessionSecret: SESSION_SECRET
  logs:
    internal: INTERNAL_LOGS
    external: EXTERNAL_LOGS

services:
  mixpanel:
    secret: MIXPANEL_SECRET
  sentry:
    dsn: SENTRY_DSN

database:
  url: DATABASE_URL

store:
  url: REDIS_URL
