api:
  http:
    port: PORT
  auth:
    jwt-signature: JWT_SIGNATURE
  logs:
    local: LOGS
    distant: LOGS_DISTANT
database:
  mongo:
    url: DATABASE_URL
services:
  mixpanel:
    secret: MIXPANEL_SECRET