api:
  http:
    port: 3000
  auth:
    jwtSecret: 'dev_secret'
    sessionSecret: 'dev_secret'
  logs:
    local: 6
    distant: 6
  security:
    cors: 'http://localhost:8080'
database:
  url:
  connection:
    host: 'localhost'
    port: 5432
    username: 'admin_user'
    password: 'admin_password'
    database: 'open_market_api'
