api:
  http:
    port: 3000
  auth:
    jwtSecret: 'dev_secret'
    sessionSecret: 'dev_secret'
  logs:
    local: 6
    distant: 6
database:
  mongo:
    url: 'mongodb://dev_user:dev_password@localhost/tom'
