env: 'development'

api:
  http:
    port: '3000'
  auth:
    jwtSecret: 'dev_secret'
    sessionSecret: 'dev_secret'
  security:
    cors:
    - 'http://localhost:8080'

database:
  connection:
    host: 'localhost'
    port: '5432'
    username: 'admin_user'
    password: 'admin_password'
    database: 'open_market_api'

store:
  url: 'redis://127.0.0.1:6379'
